### ISSUE TITLE
Missing TCCRxA = 0 in Normal Mode

### ISSUE THREAD

**Issue by xamfa** [dbuezas/arduino-web-timers#35]
I used [this](https://dbuezas.github.io/arduino-web-timers/#mcu=ATMEGA328P&timer=2&interruptA=on&OCR2A=50&interruptB=on&OCR2B=150&InterruptOnTimerOverflow=on&timerMode=Normal&clockPrescalerOrSource=64&FCPU_UI=8Mhz configuration.
)
```
/**
  * URL: https://dbuezas.github.io/arduino-web-timers/#mcu=ATMEGA328P&timer=2&interruptA=on&OCR2A=50&interruptB=on&OCR2B=150&InterruptOnTimerOverflow=on&timerMode=Normal&clockPrescalerOrSource=128&FCPU_UI=8Mhz
  * Mode     : Normal
  * Period   : 2.048 ms
  * Frequency: 488.28125 Hz
  * Outputs  : none
  */
void setup(){
  noInterrupts();
  TCCR2B = 
    1 << CS22;
  TIMSK2 = 
    1 << OCIE2B |
    1 << OCIE2A |
    1 << TOIE2;
  OCR2A = 50;
  OCR2B = 150;
  interrupts();
}
```

Somehow on my controller, TCCR2A was set to 1 but it should be 0.
I added `TCCR2A = 0;` to the code and it works fine now.

Maybe add `TCCR2A = 0;` in normal mode?

**Comment by dbuezas** [comment]
Have you set a pin as pwm output with a library maybe?

**Comment by xamfa** [comment]
You are probably right, some library must have set it. I was unable to identify the culprit but could verify, that the registers are initialized with 0. There would indeed be no point in setting everything 0 additionaly.

Sorry for the late reply. 
Closing the ticket.
Thanks!

**Comment by dbuezas** [comment]
Thanks for getting back with the update.

There's hundreds of register bits and the generated code has to ignore all zeros, otherwise it would generate a lot of code. There may be issues with timer0 since arduino initializes it internally, but I assume users of this "advanced" tool would figure that out pretty quickly, so I try to keep it "pure" for simplicity.

Anyway happy to hear you put it to good use
